F/expense fields
equinor/mad-expense-and-pay-app pull request #115
Opened 2022-05-31 20:07 UTC by tormodAase

Closes #106 #114 #83 #75

2022-06-02 11:40 UTC, dbjoEq commented on screens/Modals/ExpenseModalScreen/components/SelectExpenseType.tsx
> +    required?: boolean
Maybe call it `isRequired` ?

2022-06-02 12:06 UTC, dbjoEq submitted a review, later dismissed
Looks good. 😺

2022-06-09 12:56 UTC, dbjoEq approved these changes
Looks good. ☺️

2022-06-10 06:26 UTC, dbjoEq approved these changes
👍

2022-06-10 06:46 UTC, dbjoEq requested changes
Seems like there is a merge conflict that needs to be sorted out before merging. 👍

2022-06-10 07:11 UTC, dbjoEq approved these changes
Looks good. 🥇

2022-06-10 10:31 UTC, dbjoEq submitted a review, later dismissed
👍

2022-06-14 06:42 UTC, dbjoEq approved these changes
Looks good.

2022-06-24 12:13 UTC, dansvend reviewed
Consider using [Nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) instead of [Logical OR](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR) since Logical OR will return the second operand if the first operand is `falsy`(0 for example which might be a valid trip id?).

2022-06-24 12:25 UTC, dansvend approved these changes

2022-06-24 12:26 UTC, merged