60 the user should be able to select a pdf from the file system
equinor/mad-expense-and-pay-app pull request #122
Opened 2022-06-07 12:19 UTC by dbjoEq

2022-06-09 11:38 UTC, tormodAase requested changes
Looks good! The mad-expo-core import is a bit scary

2022-06-09 11:38 UTC, tormodAase commented on package.json
>    },
expo-image-picker can probably be removed from package.json. We don't use it anywhere else as far as I'm aware

2022-06-09 12:22 UTC, dbjoEq commented on package.json
> +    "mad-expo-core": "git+https://github.com/equinor/mad-expo-core.git",
Now pointing to newest main commit

2022-06-09 12:22 UTC, dbjoEq commented on package.json
>    },
Removed image picker!

2022-06-10 07:11 UTC, tormodAase submitted a review, later dismissed

2022-06-17 08:22 UTC, PtjeEquinor approved these changes

2022-06-17 08:23 UTC, merged