F/new travel expense screen gdexpo 69
equinor/mad-expense-and-pay-app pull request #29
Opened 2021-11-04 08:54 UTC by tormodAase

2022-04-08 08:41 UTC, SjoenH requested changes
Overall this looks really good. 💪

I haven't gotten through all the files yet, but added some comments.
Also I Found 23 typescript errors. Please have a look at those.

Seems like eslint might not be setup quite correctly (or I might need to install it globally...?)

Not that it's that important, but to reduce clutter, I like to not include code that is not in use... I understand that there's some stuff that you might not want to remove because of things coming etc... so we can allow some of that in this instance.

There's some unused imports in your files. Consider adding a eslint rule for it. 

Please also take a look at your tests and make sure they work. 

I'll need a short break from reviewing. 😅
Really appreciate the boss music. 🙏
Please re-request my review when you think it's time again.

2022-04-08 08:41 UTC, SjoenH commented on screens/Main/TravelExpensesScreen.tsx
> +
what is going on here?

2022-04-08 08:41 UTC, SjoenH commented on screens/Modals/CameraModal/CameraModalScreen.tsx
> +            }}
Does this work? Please clean up, removing things you don't need. My editor says that onPictureSaved is never called, not sure about that but... 

Could probably be done changed to something like
```ts
async () => {
  if (camera.current) {
    let photo = await camera.current.takePictureAsync();
    setPhotoURI(photo.uri);
  }
}            

```

2022-04-08 08:41 UTC, SjoenH commented on screens/Modals/CameraModal/CameraModalScreen.tsx
> +}
Lots of `{photoURI ?...:...}` without much overlap. Consider refactor into two components, one for taking picture and one for showing the picture.

2022-04-08 08:41 UTC, SjoenH commented on screens/Modals/CostObjectModalScreen/CostObjectModalScreen.tsx
> +              title={"Edit cost object"}
Element Button doesn't have required attribute busy
Element Button doesn't have required attribute disabled 

Consider making them optional

2022-04-08 08:47 UTC, SjoenH commented on components/CostObject.tsx
> +        {/*The trashiest slider label you'll ever see*/}
This is just a comment, so feel free to press resolve after reading 🙃

2022-04-08 08:48 UTC, SjoenH commented on components/AttachmentThumbnail.tsx
> +    };
This is just a comment, so feel free to press resolve after reading 🙃

2022-04-08 08:49 UTC, SjoenH commented on components/ExitWithAlert.tsx
> +        [
But in this case, it's not too bad, so just a comment.

2022-04-08 11:16 UTC, tormodAase commented on screens/Main/TravelExpensesScreen.tsx
> +
This is part of "Drag down / Scroll up to refresh list". To make sure it only sends one refetch, I've added the effect and "refreshing" state. I had some issues with multiple refetches earlier when I used isRefetching from React Query

2022-04-08 11:26 UTC, tormodAase commented on utils/CreateTravelBodyFromState.ts
> +  const departureDate = state.travelPeriod.startDate;
Fixed in new commit 572fe6f3dfae5b4294c9cdff9d96bbaf8dc36baa

2022-04-08 11:28 UTC, tormodAase commented on utils/CreateTravelBodyFromState.ts
> +        Comment: "",//expense.expenseDescription, TODO Remove comment when SAP bug is fixed
Fixed in new commit [ceb9347](https://github.com/equinor/mad-expense-and-pay-app/commit/ceb934791e91a073ce1cfb0695ddd475c6a9207e)

2022-04-08 11:35 UTC, tormodAase commented on components/AttachmentThumbnail.tsx
> +global.Buffer = global.Buffer || require("buffer").Buffer;
I don't remember the exact reason, but it's related to differences in Buffer availability in browsers and nodejs and react native

2022-04-08 11:39 UTC, tormodAase commented on components/AttachmentThumbnail.tsx
> + * @todo this component does not work as expected for the web
Yep, we need a workaround for the web in the future. Web version of Expense and pay is not prioritized. Added link to issue in new commit [96de167](https://github.com/equinor/mad-expense-and-pay-app/commit/96de1677e6fd8bbfd9752d6fdbc84171d4d261bd)

2022-04-08 11:41 UTC, SjoenH commented on components/AttachmentThumbnail.tsx
> + * @todo this component does not work as expected for the web
Would be better if API gives us a URL with a short-lived token, so that we don't need to stress with headers etc.

@anheri has done this in other apis.

2022-04-08 11:45 UTC, tormodAase commented on components/ExpenseCard.tsx
> +  useEffect(() => {
Huh, I guess you're right

2022-04-08 11:46 UTC, tormodAase commented on components/StatusChip.tsx
>      >
In this case it's because most of the styling is in the StyleSheet, but backgroundColor and borderColor are dependent on variables not accessible in the StyleSheet

2022-04-08 11:48 UTC, tormodAase commented on components/NewTravelExpenseSection.tsx
> +      medium
In this case, it's unnecessary, fixed in new commit [1c2de75](https://github.com/equinor/mad-expense-and-pay-app/commit/1c2de7591303d19ddfee88ab962448c2e4f861ab)

2022-04-08 11:49 UTC, SjoenH commented on components/NewTravelExpenseSection.tsx
> +      medium
Ok, super. 💪

2022-04-08 11:52 UTC, tormodAase commented on components/AddTravelExpenseItem.tsx
> +        style={StyleSheet.flatten([
There are other ways to merge styles, but StyleSheet.flatten is the only solution I've found that works for both native and web

2022-04-08 11:52 UTC, SjoenH commented on components/StatusChip.tsx
>      >
Ah, I see. 🤔 

I'm curious if `StyleSheet.flatten()` negates what we gain by using `StyleSheet.create()`...
Not that we ever have had any performance troubles with just using inline styling 😅

2022-04-08 11:57 UTC, SjoenH commented on components/StatusChip.tsx
>      >
Feel free to resolve this, we don't _need_ to spend more time on it.

2022-04-08 12:10 UTC, tormodAase commented on screens/Modals/CameraModal/CameraModalScreen.tsx
> +            }}
Both solutions work, but I agree your solution is more readable. Fixed in new commit [b8eace2](https://github.com/equinor/mad-expense-and-pay-app/commit/b8eace23484ba92c621c5a249da88f1799034577)

2022-04-08 12:15 UTC, tormodAase commented on screens/Modals/CostObjectModalScreen/CostObjectModalScreen.tsx
> +              title={"Edit cost object"}
They default to false https://github.com/equinor/mad-expo-core/blob/main/src/components/common/atoms/Button.tsx
But I've made an issue for it in mad-expo-core https://github.com/equinor/mad-expo-core/issues/49

2022-04-08 12:21 UTC, tormodAase commented on components/ExitWithAlert.tsx
> +        [
Fixed in new commit [5de455d](https://github.com/equinor/mad-expense-and-pay-app/commit/5de455d0464dc25a727611c8e72576ce08d5462d)

2022-04-08 12:40 UTC, tormodAase commented on components/ExpenseCard.tsx
> +  useEffect(() => {
I'm unable to make changes to this, because I'm not able to make new travels to test it on due to backend issues. Will look into it on monday

2022-04-08 13:27 UTC, tormodAase commented on screens/Modals/CameraModal/CameraModalScreen.tsx
> +}
Fixed in new commit [6bba6f3](https://github.com/equinor/mad-expense-and-pay-app/commit/6bba6f35d59e6baa29b28df08c34138afca8be07)

2022-04-08 13:51 UTC, tormodAase commented on components/AttachmentThumbnail.tsx
> + * @todo this component does not work as expected for the web
Yeah I've suggested it before, but unfortunately SAP has limitations and as far as I understand from @mglendrange and @konrad-drygas, there's no way around it..

2022-04-08 15:19 UTC, tormodAase commented on utils/Tests/DateHelper.test.ts
> +
I will use luxon to make the tests and date logic better. We don't deal with UTC, we deal with UK time thanks to SAP   🙂🔫

2022-04-08 18:39 UTC, SjoenH commented on utils/Tests/DateHelper.test.ts
> +
😂

2022-04-19 10:48 UTC, SjoenH requested changes

2022-04-19 10:48 UTC, SjoenH commented on screens/Modals/CostObjectModalScreen/CostObjectModalScreen.tsx
> +            <Button
```
Element Button doesn't have required attribute busy 
Element Button doesn't have required attribute textStyle 
Element Button doesn't have required attribute viewStyle 
```

2022-04-19 10:48 UTC, SjoenH commented on screens/Modals/DestinationsModalScreen/DestinationsModalScreen.tsx
> +            <Button
```
Element Button doesn't have required attribute busy 
```

2022-04-19 10:48 UTC, SjoenH commented on screens/Modals/DestinationsModalScreen/DestinationsModalScreen.tsx
> +        {((edit && id !== 0) || (!edit && destinations.length > 0)) && (
Hard to know what this is checking... consider making it more readable.

2022-04-19 10:48 UTC, SjoenH commented on screens/Modals/DestinationsModalScreen/DestinationsModalScreen.tsx
> +function DestinationsModalScreen(props: StackScreenProps<
This component is large and a bit hard to follow. Not sure what would help... :thinking: Sorry 😅

2022-04-19 10:48 UTC, SjoenH commented on screens/Modals/MealModalScreen/components/MealTypeTabs.tsx
> +  // const [selected, setSelected] = useState<'Breakfast' | 'Lunch' | 'Dinner'>('Breakfast');
Consider removing

2022-04-19 10:48 UTC, SjoenH commented on screens/Modals/MilageModalScreen/MilageModalScreen.tsx
> +function MilageModalScreen(
Typo. -> Should be `Mileage`
Also in the props

2022-04-20 08:24 UTC, tormodAase commented on screens/Modals/DestinationsModalScreen/DestinationsModalScreen.tsx
> +            <Button
@SjoenH I'm wondering why you get these errors, but I don't. Our typescript setup must be different.

Either way Button is from mad-expo-core, and has default props for busy and disabled

2022-04-20 08:27 UTC, SjoenH commented
I’ll take a look at it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Tormod Aase ***@***.***>
Sent: Wednesday, April 20, 2022 10:25:10 AM
To: equinor/mad-expense-and-pay-app ***@***.***>
Cc: Henry Skorpe Sjøen ***@***.***>; Mention ***@***.***>
Subject: Re: [equinor/mad-expense-and-pay-app] F/new travel expense screen gdexpo 69 (PR #29)


@tormodAase commented on this pull request.

________________________________

In screens/Modals/DestinationsModalScreen/DestinationsModalScreen.tsx<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fequinor%2Fmad-expense-and-pay-app%2Fpull%2F29%23discussion_r853864740&data=05%7C01%7Chsjo%40equinor.com%7Cb2e5c6c5e7a54f6186ee08da22a74a6e%7C3aa4a235b6e248d591957fcf05b459b0%7C0%7C0%7C637860399171903501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JuYNhoRwtUi7wDjMxbZ0FaYkG98OjIowu1TnOPV%2F2nk%3D&reserved=0>:

> +          </>
+        )}
+        <EnterTripType
+          selectedTripType={tripType}
+          setSelectedTripType={setTripType}
+        />
+        <EnterCountryAndLocation
+          countries={countries}
+          country={country}
+          location={location}
+          setCountry={setCountry}
+          setLocation={setLocation}
+        />
+        {edit ? (
+          <View style={styles.buttonContainer}>
+            <Button


@SjoenH<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSjoenH&data=05%7C01%7Chsjo%40equinor.com%7Cb2e5c6c5e7a54f6186ee08da22a74a6e%7C3aa4a235b6e248d591957fcf05b459b0%7C0%7C0%7C637860399171903501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QOjK9GrQ5S5i43otGPj6p9%2BvrgEqV%2FUjAnVKcDGAQi0%3D&reserved=0> I'm wondering why you get these errors, but I don't. Our typescript setup must be different.

Either way Button is from mad-expo-core, and has default props for busy and disabled

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fequinor%2Fmad-expense-and-pay-app%2Fpull%2F29%23discussion_r853864740&data=05%7C01%7Chsjo%40equinor.com%7Cb2e5c6c5e7a54f6186ee08da22a74a6e%7C3aa4a235b6e248d591957fcf05b459b0%7C0%7C0%7C637860399171903501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JuYNhoRwtUi7wDjMxbZ0FaYkG98OjIowu1TnOPV%2F2nk%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAYEPIJNJQI63VAHN2BFIALVF65ONANCNFSM5HK4ZCBQ&data=05%7C01%7Chsjo%40equinor.com%7Cb2e5c6c5e7a54f6186ee08da22a74a6e%7C3aa4a235b6e248d591957fcf05b459b0%7C0%7C0%7C637860399171903501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qcTrmRQFPo7UH8Uc4VJyaa4AI0RMcC9pGx2BlVmA2oY%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


-------------------------------------------------------------------
The information contained in this message may be CONFIDENTIAL and is
intended for the addressee only. Any unauthorized use, dissemination of the
information or copying of this message is prohibited. If you are not the
addressee, please notify the sender immediately by return e-mail and delete
this message.
Thank you

2022-04-20 08:30 UTC, SjoenH commented on screens/Modals/DestinationsModalScreen/DestinationsModalScreen.tsx
> +            <Button
I’ll take a look at it.

2022-04-20 08:32 UTC, SjoenH commented on screens/Modals/DestinationsModalScreen/DestinationsModalScreen.tsx
> +            <Button
All props seem to be required.

In `node_modules/mad-expo-core/src/components/common/atoms/Button.tsx`:
```tsx

const Button = (props: {
  title: string | JSX.Element;
  onPress: (event: GestureResponderEvent) => void;
  textStyle: Object;
  viewStyle: Object;
  disabled: boolean;
  busy: boolean;
}) => {
...
```

2022-04-21 09:47 UTC, tormodAase commented on components/ExpenseCard.tsx
> +  }, [data]);
Fixed in new commit https://github.com/equinor/mad-expense-and-pay-app/pull/29/commits/6fbe0881b4fa18ca044587481d7f7e3de0498322

2022-04-21 09:58 UTC, tormodAase commented on components/ExpenseCard.tsx
> +  }, [data]);
Removed useEffect in new commit https://github.com/equinor/mad-expense-and-pay-app/pull/29/commits/a924120925d7e57200aee5fc2ace1197fd97579c

2022-04-21 10:04 UTC, tormodAase commented on components/Destination.tsx
> +                : 'No travel period selected'}
It's the same. fixed in new commit https://github.com/equinor/mad-expense-and-pay-app/pull/29/commits/5b5ed493ff7d3436b1ea71ec6ced8551ee4500e4

2022-04-21 10:09 UTC, tormodAase commented on configs/SettingsConfig.tsx
> +  // {icon: "feedback", title: "Feedback", route: "Feedback"},
Fixed in new commit [f2af3da](https://github.com/equinor/mad-expense-and-pay-app/pull/29/commits/f2af3daf97e1caa7dee46d196a0e1c103a7a4f8b)

2022-04-21 10:09 UTC, tormodAase commented on components/common/Expense/DynamicInputs.tsx
> +  //  return <Typography>ERROR: No expense types available</Typography>;
Fixed in new commit [f2af3da](https://github.com/equinor/mad-expense-and-pay-app/pull/29/commits/f2af3daf97e1caa7dee46d196a0e1c103a7a4f8b)

2022-04-21 10:09 UTC, tormodAase commented on screens/Modals/MealModalScreen/components/MealTypeTabs.tsx
> +  // const [selected, setSelected] = useState<'Breakfast' | 'Lunch' | 'Dinner'>('Breakfast');
Fixed in new commit [f2af3da](https://github.com/equinor/mad-expense-and-pay-app/pull/29/commits/f2af3daf97e1caa7dee46d196a0e1c103a7a4f8b)

2022-04-21 10:16 UTC, tormodAase commented on screens/Modals/MilageModalScreen/MilageModalScreen.tsx
> +function MilageModalScreen(
Fixed in new commit [7a98e77](https://github.com/equinor/mad-expense-and-pay-app/pull/29/commits/7a98e778f9b89e5678de73875d68b84c4fe85223)

2022-04-21 10:30 UTC, tormodAase commented on components/common/Expense/DynamicInputs.tsx
> +  const [showOptions, toggleShowOptions] = useState(false);
Fixed in new commit [e0b2708](https://github.com/equinor/mad-expense-and-pay-app/pull/29/commits/e0b2708f3831c3000123ca3eb31824308a8a3bdd)

2022-04-21 10:54 UTC, tormodAase commented on screens/Modals/DestinationsModalScreen/DestinationsModalScreen.tsx
> +        {((edit && id !== 0) || (!edit && destinations.length > 0)) && (
Made the code a bit easier to read in new commit https://github.com/equinor/mad-expense-and-pay-app/pull/29/commits/fb6ff5ebb8fd341da63b2c642d99c652fc3dba2a

2022-04-21 10:54 UTC, tormodAase commented on screens/Modals/DestinationsModalScreen/DestinationsModalScreen.tsx
> +function DestinationsModalScreen(props: StackScreenProps<
Made the code a bit easier to read in new commit https://github.com/equinor/mad-expense-and-pay-app/pull/29/commits/fb6ff5ebb8fd341da63b2c642d99c652fc3dba2a

2022-04-21 11:15 UTC, tormodAase commented
I've looked into all of your comments and made some changes. Also fixed the crash that Natalie found

2022-04-21 12:38 UTC, SjoenH requested changes

2022-04-21 12:38 UTC, SjoenH commented on components/ExpenseCard.tsx
> +  const deleteTravelMutation = useMutation(() => deleteTravel(id), { onSuccess: () => refetch() });
Try to use invalidateQuery instead https://react-query.tanstack.com/guides/query-invalidation#_top

2022-04-22 12:58 UTC, SjoenH requested changes

2022-04-22 12:58 UTC, SjoenH commented on screens/Modals/ExpenseModalScreen/ExpenseModalScreen.tsx
> +
Also, I prefer dumber components. More functional component like. Present what it is given. etc... 🙃

2022-04-22 12:58 UTC, SjoenH commented on screens/Modals/ExpenseModalScreen/ExpenseModalScreen.tsx
> +
Also, also... 👁️ https://react-hook-form.com 👁️

2022-04-22 12:58 UTC, SjoenH commented on screens/Modals/SelectDateAndTimeModalScreen/SelectDateAndTimeModalScreen.tsx
> +  );
Try using the implicit type instead.

ALso, you mentioned some strange logic edge-case that you might want to look at?

2022-04-22 12:58 UTC, SjoenH commented on screens/Modals/SelectDateAndTimeModalScreen/components/TimeView.tsx
> +  date = date.set({ hour: props.time.hours, minute: props.time.minutes });
ONeline please 
``const date = DateTime.now().set({ hour: props.time.hours, minute: props.time.minutes });``

2022-04-22 12:58 UTC, SjoenH commented on utils/DateHelper.ts
> +}
Please refactor to use Luxon formatting instead

```ts
return date.toFormat('dd.MM.yyyy');
```

here and there 👍

2022-04-22 12:58 UTC, SjoenH commented on screens/Modals/SelectDateAndTimeModalScreen/utils/GetMarkedDates.ts
> +}
Consider writing some tests for this. Hard to do refactoring. Also, if you find the return type. Please add it :D

2022-04-22 12:58 UTC, SjoenH commented on screens/Modals/SelectDateAndTimeModalScreen/utils/GetMarkedDates.ts
> +      },
Does it make sense to have a date between... let's say... the 1 of April and the 1 of April? the same year?

2022-04-22 13:36 UTC, tormodAase commented on screens/Modals/SelectDateAndTimeModalScreen/components/TimeView.tsx
> +  date = date.set({ hour: props.time.hours, minute: props.time.minutes });
Fixed

2022-04-25 07:31 UTC, SjoenH requested changes

2022-04-25 07:31 UTC, SjoenH commented on screens/NewTravelExpense/RefundsTab/RefundsTab.tsx
> +            key={JSON.stringify(expense)}
🤔 Don't you have a better key?

2022-04-25 08:04 UTC, tormodAase commented on screens/NewTravelExpense/RefundsTab/RefundsTab.tsx
> +            key={JSON.stringify(expense)}
Now using expense.uuid instead

2022-04-25 08:28 UTC, tormodAase commented on screens/NewTravelExpense/AttachmentsTab/AttachmentsTab.tsx
> +    (async () => {
Rewritten

2022-04-25 08:28 UTC, tormodAase commented on screens/NewTravelExpense/AttachmentsTab/AttachmentsTab.tsx
> +      if (Platform.OS !== 'web') {
Rewritten

2022-04-25 11:37 UTC, tormodAase commented on screens/NewTravelExpense/NewTravelExpenseScreen.tsx
> +  }, [confirmedAndSent]);
Fixed

2022-04-25 11:51 UTC, tormodAase commented on utils/DateHelper.ts
> +}
Rewrote some of the helper functions

2022-04-25 12:22 UTC, tormodAase commented on components/ExpenseCard.tsx
> +          ))}
Fixed. Displays 'Error' if request failed

2022-04-25 19:06 UTC, SjoenH requested changes

2022-04-26 07:51 UTC, tormodAase commented on screens/NewTravelExpense/RefundsTab/RefundsTab.tsx
> +  const AccomodationInput = MealInput;
Fixed all accommodation typos

2022-04-26 07:51 UTC, tormodAase commented on screens/NewTravelExpense/RefundsTab/RefundsTab.tsx
> +          type="Private accomodation"
Fixed all accommodation typos

2022-04-26 07:52 UTC, tormodAase commented on screens/NewTravelExpense/RefundsTab/RefundsTab.tsx
> +      <NewTravelExpenseSection title="Accomodation">
Fixed all accommodation typos

2022-04-26 07:52 UTC, tormodAase commented on screens/NewTravelExpense/RefundsTab/components/MealInput.tsx
> +  const accomodation = useStoreState((state) => state.accomodation);
Fixed all accommodation typos

2022-04-26 07:52 UTC, tormodAase commented on screens/NewTravelExpense/RefundsTab/components/MealInput.tsx
> +  const field = props.type === 'Private accomodation'
Fixed all accommodation typos

2022-04-26 07:55 UTC, tormodAase commented on screens/NewTravelExpense/RefundsTab/components/MealInput.tsx
> +    ? getDatesBetweenAndIncluding(
I don't believe it is expensive in our use case, but I'll consider using useMemo incase that one guy has a travel period of 3 years

2022-04-26 07:58 UTC, tormodAase commented on screens/NewTravelExpense/RefundsTab/RefundsTab.tsx
> +          title="Add milage"
Fixed the remaining Mileage typos

2022-04-26 08:00 UTC, tormodAase commented on screens/NewTravelExpense/SummaryTab/SummaryTab.tsx
> +                    <MissingPrimaryText>No triptype</MissingPrimaryText>
Grammarly working overtime

2022-04-26 08:03 UTC, tormodAase commented on screens/NewTravelExpense/SummaryTab/SummaryTab.tsx
> +                    <MissingPrimaryText>No triptype</MissingPrimaryText>
Fixed

2022-04-26 08:08 UTC, tormodAase commented on screens/NewTravelExpense/SummaryTab/components/Meal.tsx
> +        onValueChange={() => ''}
Left a comment inside onValueChange. Checkbox is only displayed for aesthetic purposes, and is not functional

2022-04-26 08:14 UTC, tormodAase commented on utils/DateHelper.ts
> +    .padStart(2, '0')}:${date.minute.toString().padStart(2, '0')}`;
Fixed! Correct solution was: date.toFormat('cccc LLLL dd, yyyy, HH:mm');

2022-04-26 08:16 UTC, tormodAase commented on utils/DateHelper.ts
> +  return dateArray;
Simplified!

2022-04-26 08:19 UTC, SjoenH commented on screens/NewTravelExpense/RefundsTab/components/MealInput.tsx
> +    ? getDatesBetweenAndIncluding(
Haha! Thank you 😆

2022-04-26 08:27 UTC, tormodAase commented on utils/DateHelper.ts
> +}
It's not as simple as that.
![image](https://user-images.githubusercontent.com/22524448/165255673-43bf7b98-b4a7-44b3-b394-7577d4ec9ac1.png)

If start and end date's year is equal, the start date's year should not be displayed.

I've simplified it to this:
```tsx
// TravelPeriod => 'DD MON YYYY - DD MON YYYY'
// (example: '21 nov - 30 nov 2021', '30 dec 2021 - 04 jan 2022')
export function getShortTravelPeriod(travelPeriod: TravelPeriod) {
  if (!travelPeriod.startDate || !travelPeriod.endDate) return null;
  const startDate = travelPeriod.startDate.year !== travelPeriod.endDate.year
    ? travelPeriod.startDate.toFormat('dd LLL yyyy')
    : travelPeriod.startDate.toFormat('dd LLL');
  const endDate = travelPeriod.endDate.toFormat('dd LLL yyyy');
  return `${startDate} - ${endDate}`.toLowerCase();
}
```

2022-04-26 09:37 UTC, tormodAase commented on screens/NewTravelExpense/NewTravelExpenseScreen.tsx
> +  const ActivePage = pages[activeTab];
In the future we will most likely add proper tabs to make the app more user friendly with features like swipe to switch tab, but for now this works well 👍

2022-04-28 11:50 UTC, tormodAase commented on screens/NewTravelExpense/SummaryTab/SummaryTab.tsx
> +                    </ValueText>
Fixed

2022-04-28 12:08 UTC, tormodAase commented on screens/NewTravelExpense/TravelDetailsTab/TravelDetailsTab.tsx
> +            key={JSON.stringify(destination)}
Now using destination.uuid

2022-04-28 12:44 UTC, tormodAase commented on utils/DateHelper.ts
> +  return !!array.find((item) => item.toMillis() === value.toMillis());
Using ```Array.some()``` instead.
I compare millis because the comparison fails if I compare DateTime objects
![image](https://user-images.githubusercontent.com/22524448/165753437-6cd6ce72-b2c0-4a0b-aa2f-892d178a7e09.png)
![image](https://user-images.githubusercontent.com/22524448/165753504-74e4d1de-1fcd-46f5-ae9a-41a0fcfeb403.png)


![image](https://user-images.githubusercontent.com/22524448/165753655-b25dc040-d2ae-4fc7-a57f-373c8d6c2c93.png)
![image](https://user-images.githubusercontent.com/22524448/165753705-7f4a9916-4d84-41bc-9b14-bad57f7f2b6f.png)

I would prefer to separate it into it's own function since, like you said, toMillis() might cause confusion.

2022-04-28 12:45 UTC, tormodAase commented on utils/DateHelper.ts
> +  return !!array.find((item) => item.toMillis() === value.toMillis());
![image](https://user-images.githubusercontent.com/22524448/165754849-3f5f4852-4961-4a60-acd6-f18f4eb21367.png)
I added more comments and doc to make it clear what that function does

2022-04-28 12:50 UTC, SjoenH commented on utils/DateHelper.ts
> +  return !!array.find((item) => item.toMillis() === value.toMillis());
Comparing the object values instead of the objects themselves is a good idea as you say.
I'm still not sold on having it as its own function, but it's fine if you do.

Consider renaming the function to something date-related

2022-04-28 13:18 UTC, tormodAase commented on screens/Modals/MealModalScreen/MealModalScreen.tsx
> +  };
Updated with comments. Take a look and let me know if it should be refactored

2022-04-28 13:18 UTC, tormodAase commented on screens/Modals/MealModalScreen/MealModalScreen.tsx
> +  };
Updated with comments. Take a look and let me know if it should be refactored

2022-04-28 13:21 UTC, tormodAase commented on screens/NewTravelExpense/SummaryTab/SummaryTab.tsx
> +                  key={attachment.uri ? attachment.uri : attachment.sapBinaryMetaData?.DocumentId}
Not sure what you're asking about

2022-04-28 13:52 UTC, tormodAase commented on screens/NewTravelExpense/RefundsTab/components/MealInput.tsx
> +    ? getDatesBetweenAndIncluding(
Fixed. Made the getNumberOfDaysBetween function and am using that instead. Did not implement useMemo, as I didn't find any major performance issues even with a travel period of 31 years

2022-04-28 13:52 UTC, tormodAase commented on screens/NewTravelExpense/SummaryTab/SummaryTab.tsx
> +    ? getDatesBetweenAndIncluding(
Fixed. Made the getNumberOfDaysBetween function and am using that instead. Did not implement useMemo, as I didn't find any major performance issues even with a travel period of 31 years

2022-04-28 20:11 UTC, tormodAase commented on screens/NewTravelExpense/TravelDetailsTab/TravelDetailsTab.tsx
> +                />
uuid is now used as id for destinations, costobjects and expenses both as params (when navigating) and for actions (deleteDestination, editDestination, etc.)

2022-04-28 20:12 UTC, tormodAase commented on screens/NewTravelExpense/TravelDetailsTab/TravelDetailsTab.tsx
> +              params: { id: index },
uuid is now used as id for destinations, costobjects and expenses both as params (when navigating) and for actions (deleteDestination, editDestination, etc.)

2022-04-28 20:12 UTC, tormodAase commented on screens/Modals/ExpenseModalScreen/ExpenseModalScreen.tsx
> +
Fixed

2022-04-28 20:17 UTC, tormodAase commented on screens/NewTravelExpense/NewTravelExpenseScreen.tsx
> +function NewTravelExpenseScreen(props: StackScreenProps<
Renamed to TravelExpenseScreen

2022-04-28 20:54 UTC, tormodAase commented on screens/NewTravelExpense/SummaryTab/SummaryTab.tsx
> +                        : destinations[index + 1].departureFromPreviousLocation,
Separated the logic into it's own function, and typed extensive documentation for what it does

2022-04-28 20:59 UTC, tormodAase commented
I've yet to make significant changes to SelectDateAndTimeModalScreen.tsx and GetMarkedDates.ts, so please ignore those for now. I will have a look at them tomorrow. Otherwise I've made several changes, and everything else is now ready for re-review.

2022-04-28 21:07 UTC, tormodAase commented on utils/DateHelper.ts
> +  return !!array.find((item) => item.toMillis() === value.toMillis());
renamed to dateIsInArray

2022-04-28 21:17 UTC, tormodAase commented on screens/NewTravelExpense/SummaryTab/SummaryTab.tsx
> +                  key={attachment.uri ? attachment.uri : attachment.sapBinaryMetaData?.DocumentId}
Yes. If you select an attachment on your device, or take a picture, the uri to that file will be saved to attachment.uri while you're working on that travel expense.
If you exit the travel expense and reopen it from SAP, the attachment data will be saved to attachment.sapBinaryMetaData.

Duplicate keys could happen if the user adds the same attachment from device multiple times, so I should probably add a uuid to each attachment and use that as key instead

2022-05-02 11:21 UTC, SjoenH requested changes
Empty file ? -> `services/AuthenticateSilently.ts`

2022-05-05 15:02 UTC, tormodAase commented on screens/Modals/SelectDateAndTimeModalScreen/utils/GetMarkedDates.ts
> +}
Fixed. this function is now vastly simplified. Also now returns a Record (got rid of the JSON.parse)

2022-05-05 15:11 UTC, tormodAase commented on screens/Modals/SelectDateAndTimeModalScreen/SelectDateAndTimeModalScreen.tsx
> +  );
This component is now vastly simplified

2022-05-05 15:16 UTC, tormodAase commented on screens/NewTravelExpense/SummaryTab/SummaryTab.tsx
> +                  key={attachment.uri ? attachment.uri : attachment.sapBinaryMetaData?.DocumentId}
Created issue for looking into this at a later date
https://github.com/equinor/mad-expense-and-pay-app/issues/78

2022-05-05 15:26 UTC, tormodAase commented on screens/NewTravelExpense/TravelExpenseScreen.tsx
> +  // const [tabs, setTabs] = useState({icon:})
Removed

2022-05-09 10:17 UTC, SjoenH approved these changes

2022-05-09 10:18 UTC, SjoenH commented
Ready for testing 💪

2022-05-11 14:03 UTC, dansvend approved these changes
Looks good💪

2022-05-11 14:03 UTC, merged